### ISSUE TITLE
bitbuf_num representation error after initializing with init_str

### ISSUE THREAD

**Issue by sthkindacrazy** [mkchoi212/bitbuf#1]
`0xdeadbeef` should be 3735928559 in decimal. 
But below test script does not fit with the expectation. 

`bitbuf b = BITBUF_INIT;
 bitbuf_init_str(&b, "0xdeadbeef");
 printf("num : %lu\n", bitbuf_num(&b));`

result. 
`num : 14593470`

guess it requires logic increasing `bitbuf->len, alloc`

**Comment by mkchoi212** [comment]
The current version of `bitbuf_num` supports integers that can fit into `unsigned long`. You go and try to implement it :)

*change unsigned long to unsigned long long*

**Comment by mkchoi212** [comment]
Fixed with a5c351dbe339e92f442a4c59960b293eb6566fa5 😄
